# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=net.kognition.inscribed
archives_base_name=inscribed

# Dependencies
fabric_api_version=0.161.0+26.3

mixinsquared_version=0.3.4

acornlib_version=1.0.8+26.3

modmenu_version=21.0.0
midnightlib_version=1.9.3+26.3-fabric

cca_version=8.1.0
